const Listening = require('../models/listing')
const mongoose = require("mongoose")
const mongourl = "mongodb://127.0.0.1:27017/GetPet"
 function connectdb(){
    mongoose.connect(mongourl)
    .then((res)=>{
        console.log("database connect succesfully");
    })
    .catch((e)=>{
        console.log("database not connected")
    })
}
connectdb()


Listening.insertMany([
        {
          pet_id: '134445',
          seller_id: '67890',
          pet_name: 'Buddy',
          pet_type: 'Dog',
          breed: 'Golden Retriever',
          age: 2,
          description: 'Friendly and playful dog, great with kids.',
          location: 'New York, USA',
          image: 'https://example.com/images/golden_retriever.jpg',
          price: 500,
        },
        {
          pet_id: '134446',
          seller_id: '67891',
          pet_name: 'Whiskers',
          pet_type: 'Cat',
          breed: 'Persian',
          age: 3,
          description: 'Calm and affectionate cat, loves being indoors.',
          location: 'Los Angeles, USA',
          image: 'https://example.com/images/persian_cat.jpg',
          price: 300,
        },
        {
          pet_id: '134447',
          seller_id: '67892',
          pet_name: 'Charlie',
          pet_type: 'Dog',
          breed: 'Beagle',
          age: 1,
          description: 'Energetic and playful, great for outdoor activities.',
          location: 'Chicago, USA',
          image: 'https://example.com/images/beagle.jpg',
          price: 450,
        },
        {
          pet_id: '134448',
          seller_id: '67893',
          pet_name: 'Mittens',
          pet_type: 'Cat',
          breed: 'Siamese',
          age: 2,
          description: 'Loyal and vocal, loves human interaction.',
          location: 'Houston, USA',
          image: 'https://example.com/images/siamese_cat.jpg',
          price: 350,
        },
        {
          pet_id: '134449',
          seller_id: '67894',
          pet_name: 'Max',
          pet_type: 'Dog',
          breed: 'German Shepherd',
          age: 4,
          description: 'Brave and intelligent, perfect for families.',
          location: 'San Francisco, USA',
          image: 'https://example.com/images/german_shepherd.jpg',
          price: 600,
        },
        {
          pet_id: '134450',
          seller_id: '67895',
          pet_name: 'Luna',
          pet_type: 'Cat',
          breed: 'British Shorthair',
          age: 1,
          description: 'Quiet and friendly, great for small apartments.',
          location: 'Miami, USA',
          image: 'https://example.com/images/british_shorthair.jpg',
          price: 400,
        },
        {
          pet_id: '134451',
          seller_id: '67896',
          pet_name: 'Duke',
          pet_type: 'Dog',
          breed: 'Labrador Retriever',
          age: 3,
          description: 'Friendly and energetic, loves swimming.',
          location: 'Seattle, USA',
          image: 'https://example.com/images/labrador_retriever.jpg',
          price: 550,
        },
        {
          pet_id: '134452',
          seller_id: '67897',
          pet_name: 'Bella',
          pet_type: 'Dog',
          breed: 'Poodle',
          age: 2,
          description: 'Smart and easy to train, perfect for allergy sufferers.',
          location: 'Denver, USA',
          image: 'https://example.com/images/poodle.jpg',
          price: 500,
        },
        {
          pet_id: '134453',
          seller_id: '67898',
          pet_name: 'Shadow',
          pet_type: 'Dog',
          breed: 'Doberman',
          age: 3,
          description: 'Loyal and protective, ideal for guard duties.',
          location: 'Dallas, USA',
          image: 'https://example.com/images/doberman.jpg',
          price: 650,
        },
        {
          pet_id: '134454',
          seller_id: '67899',
          pet_name: 'Nala',
          pet_type: 'Cat',
          breed: 'Maine Coon',
          age: 4,
          description: 'Gentle and friendly, great for families with kids.',
          location: 'Las Vegas, USA',
          image: 'https://example.com/images/maine_coon.jpg',
          price: 450,
        },
        {
          pet_id: '134455',
          seller_id: '67900',
          pet_name: 'Simba',
          pet_type: 'Dog',
          breed: 'Rottweiler',
          age: 2,
          description: 'Confident and courageous, excellent guard dog.',
          location: 'Austin, USA',
          image: 'https://example.com/images/rottweiler.jpg',
          price: 600,
        },
        {
          pet_id: '134456',
          seller_id: '67901',
          pet_name: 'Smokey',
          pet_type: 'Cat',
          breed: 'Russian Blue',
          age: 3,
          description: 'Quiet and reserved, loves to relax in quiet spaces.',
          location: 'San Diego, USA',
          image: 'https://example.com/images/russian_blue.jpg',
          price: 350,
        },
        {
          pet_id: '134457',
          seller_id: '67902',
          pet_name: 'Rocky',
          pet_type: 'Dog',
          breed: 'Boxer',
          age: 2,
          description: 'Energetic and playful, perfect for active owners.',
          location: 'Phoenix, USA',
          image: 'https://example.com/images/boxer.jpg',
          price: 550,
        },
        {
          pet_id: '134458',
          seller_id: '67903',
          pet_name: 'Cleo',
          pet_type: 'Cat',
          breed: 'Bengal',
          age: 1,
          description: 'Active and curious, loves climbing and exploring.',
          location: 'San Antonio, USA',
          image: 'https://example.com/images/bengal.jpg',
          price: 500,
        },
        {
          pet_id: '134459',
          seller_id: '67904',
          pet_name: 'Bruno',
          pet_type: 'Dog',
          breed: 'Bulldog',
          age: 3,
          description: 'Gentle and friendly, perfect for laid-back owners.',
          location: 'Philadelphia, USA',
          image: 'https://example.com/images/bulldog.jpg',
          price: 450,
        },
        {
          pet_id: '134460',
          seller_id: '67905',
          pet_name: 'Toby',
          pet_type: 'Dog',
          breed: 'Corgi',
          age: 2,
          description: 'Playful and fun-loving, great for kids.',
          location: 'Portland, USA',
          image: 'https://example.com/images/corgi.jpg',
          price: 400,
        },
        {
          pet_id: '134461',
          seller_id: '67906',
          pet_name: 'Gizmo',
          pet_type: 'Cat',
          breed: 'Sphynx',
          age: 3,
          description: 'Curious and energetic, loves being the center of attention.',
          location: 'Orlando, USA',
          image: 'https://example.com/images/sphynx.jpg',
          price: 600,
        },
        {
          pet_id: '134462',
          seller_id: '67907',
          pet_name: 'Leo',
          pet_type: 'Dog',
          breed: 'Husky',
          age: 4,
          description: 'Friendly and energetic, loves outdoor activities.',
          location: 'Salt Lake City, USA',
          image: 'https://example.com/images/husky.jpg',
          price: 550,
        },
        {
          pet_id: '134463',
          seller_id: '67908',
          pet_name: 'Zoe',
          pet_type: 'Cat',
          breed: 'Abyssinian',
          age: 2,
          description: 'Active and affectionate, loves being involved in everything.',
          location: 'Atlanta, USA',
          image: 'https://example.com/images/abyssinian.jpg',
          price: 400,
        },
        {
          pet_id: '134464',
          seller_id: '67909',
          pet_name: 'Rex',
          pet_type: 'Dog',
          breed: 'Pit Bull',
          age: 3,
          description: 'Strong and protective, loyal to its family.',
          location: 'Baltimore, USA',
          image: 'https://example.com/images/pitbull.jpg',
          price: 500,
        },
        {
          pet_id: '134465',
          seller_id: '67910',
          pet_name: 'Oliver',
          pet_type: 'Cat',
          breed: 'Scottish Fold',
          age: 2,
          description: 'Quiet and friendly, loves cuddling.',
          location: 'Boston, USA',
          image: 'https://example.com/images/scottish_fold.jpg',
          price: 450,
        },
        {
          pet_id: '134466',
          seller_id: '67911',
          pet_name: 'Bailey',
          pet_type: 'Dog',
          breed: 'Shih Tzu',
          age: 3,
          description: 'Loyal and affectionate, loves being pampered.',
          location: 'Minneapolis, USA',
          image: 'https://example.com/images/shih_tzu.jpg',
          price: 350,
        },
        {
          pet_id: '134467',
          seller_id: '67912',
          pet_name: 'Willow',
          pet_type: 'Cat',
          breed: 'Ragdoll',
          age: 1,
          description: 'Gentle and laid-back, loves being carried around.',
          location: 'Nashville, USA',
          image: 'https://example.com/images/ragdoll.jpg',
          price: 500,
        },
        {
          pet_id: '134468',
          seller_id: '67913',
          pet_name: 'Oscar',
          pet_type: 'Dog',
          breed: 'Chihuahua',
          age: 2,
          description: 'Small and brave, perfect for city living.',
          location: 'San Jose, USA',
          image: 'https://example.com/images/chihuahua.jpg',
          price: 300,
        },
        {
          pet_id: '134469',
          seller_id: '67914',
          pet_name: 'Milo',
          pet_type: 'Dog',
          breed: 'Border Collie',
          age: 3,
          description: 'Intelligent and active, loves herding and running.',
          location: 'Charlotte, USA',
          image: 'https://example.com/images/border_collie.jpg',
          price: 600,
        },
        {
          pet_id: '134470',
          seller_id: '67915',
          pet_name: 'Rosie',
          pet_type: 'Cat',
          breed: 'Himalayan',
          age: 2,
          description: 'Calm and affectionate, perfect for quiet homes.',
          location: 'Detroit, USA',
          image: 'https://example.com/images/himalayan.jpg',
          price: 400,
        },
        {
          pet_id: '134471',
          seller_id: '67916',
          pet_name: 'Zeus',
          pet_type: 'Dog',
          breed: 'Great Dane',
          age: 4,
          description: 'Gentle giant, loves being around people.',
          location: 'Indianapolis, USA',
          image: 'https://example.com/images/great_dane.jpg',
          price: 700,
        },
        {
          pet_id: '134472',
          seller_id: '67917',
          pet_name: 'Chloe',
          pet_type: 'Cat',
          breed: 'Turkish Angora',
          age: 3,
          description: 'Elegant and friendly, loves attention.',
          location: 'Milwaukee, USA',
          image: 'https://example.com/images/turkish_angora.jpg',
          price: 450,
        },
        {
          pet_id: '134473',
          seller_id: '67918',
          pet_name: 'Rufus',
          pet_type: 'Dog',
          breed: 'Dachshund',
          age: 2,
          description: 'Curious and brave, loves digging and exploring.',
          location: 'Louisville, USA',
          image: 'https://example.com/images/dachshund.jpg',
          price: 400,
        },
      ])
      .then((res)=>{
        console.log("data inserted")
      })